myTodoList/urls.py
from django.contrib import admin
from django.urls import path, include
from todoList import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls))
]

todoList/urls.py
from django.urls import path
from . import views
from . import followSystemViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    # accounts url
    path('', views.index, name="Login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='login'),
    path('register/', views.userRegister, name="Register"),
    # todo functions page
    path('dashboard/', views.dashboard, name="Dashboard"),
    path('add-item/', views.addItem, name="Add Item"),
    path('remove-item/<int:id>/', views.removeItem, name="Remove"),
    path('edit-item/<int:id>/', views.editItem, name="Edit"),
    path('friends-todo/',views.friendsTodo, name="Friends Todo"),
    path('get-friends-todo/<int:friendId>/',views.getFriendsTodo, name="Get Friends Todo"),
    path('save-friend-todo/',views.saveFriendTodo, name="Save Friend Todo"),
    # user activities page
    path('activities/', views.activities, name="Activities"),
    path('remove-activity/<int:id>/', views.removeActivities, name="Activities"),
    # follower systems page url
    path('explore/', followSystemViews.exploreUsers, name="Users"),
    path('follow/', followSystemViews.followUsers, name="Follow"),
    path('unfollow/', followSystemViews.unFollowUsers, name="Unfollow"),
    path('followers/', followSystemViews.userFollowers, name="Followers"),
    path('friends/', followSystemViews.userFriends, name="Friends")

]

todoList/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class TodoItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="users")
    todo_name = models.CharField(max_length=200)
    start_date= models.DateField()
    end_date= models.DateField()
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('created',)

    def natural_key(self):
        return (self.todo_name, self.start_date, self.end_date)


class UserActions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    action_name = models.CharField(max_length=200)
    action_detail = models.CharField(max_length=500)
    created = created = models.DateTimeField(default=timezone.now)


class UserContacts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    friends = models.BooleanField()

todoList/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import TodoItem

class LoginForm(forms.Form):
    username = forms.CharField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegister(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def cleanPassword2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('password not match')
        return cd['password2']

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('todo_name', 'start_date', 'end_date')

todoList/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm,UserRegister,TodoItemForm
from django.http import HttpResponse
from .models import TodoItem,UserActions,UserContacts
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from django.core import serializers

@csrf_exempt
def index(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username= cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('/dashboard/')
                else:
                    HttpResponse('User not active')
            else:
                HttpResponse('Invalid credentials')
    else:
        form = LoginForm()
    return render(request , 'account/login.html', {'form':form})
    

def dashboard(request):
    todoList = TodoItem.objects.all().filter(user_id = request.user.id)
    return render(request , 'todo-screens/dashboard.html', {'todo_list':todoList})


def userRegister(request):
    if request.method == "POST":
        form = UserRegister(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return redirect('/')
    else:
        form = UserRegister()
    return render(request, 'account/register.html', {'form':form})


def addItem(request):
    if request.method == 'POST':
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user_id = request.user.id
            new_form.save()
            action_name = new_form.todo_name+' Added'
            action_detail = request.user.first_name+' '+request.user.last_name+' added '+new_form.todo_name+' in list.'
            userActivityHandler(request, action_name, action_detail)
            return redirect('/dashboard')
    else:
        form = TodoItemForm()
    return render(request, 'todo-screens/todo-form.html', {'form':form})


def removeItem(request, id):
    item = TodoItem.objects.get(id=id)
    item.delete()
    action_name = item.todo_name+' removed'
    action_detail = request.user.first_name+' '+request.user.last_name+' remove '+item.todo_name+' from list.'
    userActivityHandler(request, action_name, action_detail)
    return redirect('/dashboard')


def editItem(request, id):
    selectedItem = get_object_or_404(TodoItem, id=id)
    form = TodoItemForm(request.POST or None,instance=selectedItem)
    if request.method == 'POST':
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
            return redirect('/dashboard')
    return render(request, 'todo-screens/todo-form.html', {'form':form, 'item':selectedItem})


def userActivityHandler(request, name, detail):
    UserActions.objects.create(user = request.user, action_name = name, action_detail= detail);


def activities(request):
    user_activities = UserActions.objects.all().filter(user_id=request.user.id)
    return render(request, 'todo-screens/activities.html', {'activities': user_activities})


def removeActivities(request, id):
    item = UserActions.objects.get(id=id)
    item.delete()
    return redirect('/activities')


def friendsTodo(request):
    allFriends = UserContacts.objects.all().filter(user_id=request.user.id,friends=True)
    return render(request, 'todo-screens/friendsTodoList.html', {'friends':allFriends})
    

@csrf_exempt
def getFriendsTodo(request, friendId):
    if friendId:
        todoItems = TodoItem.objects.all().filter(user_id=friendId)
        data = serializers.serialize('json', todoItems, fields=('todo_name','start_date','end_date'), use_natural_foreign_keys=True, use_natural_primary_keys=True)
    return JsonResponse({'friendTodos':data})


@csrf_exempt
def saveFriendTodo(request):
    data = request.GET
    res = {}
    if request.method == "GET":
        if data:
            TodoItem.objects.create(todo_name=data['todo_name'], start_date=data['start_date'], end_date=data['end_date'], user=request.user)
            action_name = data['todo_name']+' Saved'
            action_detail = request.user.first_name+' '+request.user.last_name+' saved '+data['todo_name']+' from friends todos.'
            userActivityHandler(request, action_name, action_detail)
            res = {'code':200, 'data': data}
    else:
        res = {error: 'something went wrong'}
    return JsonResponse(res)

todoList/templates/add-item.html
{% extends 'base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block content %}

        <div class="container-fluid">
                
            <div class="row no-gutter">
                <div class="col-md-12 bg-light">
                    <div class="login d-flex align-items-center py-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-10 col-xl-7 mx-auto">
                                    <h3 class="display-4">Add Item</h3>
                                    <form action="." method="post">
                                        {% csrf_token %}
                                        <div class="form-group mb-3">
                                            {{ form.todo_name }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.start_date }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.end_date }}
                                        </div>
                                        <div class="custom-control custom-checkbox mb-3 pl-0">
                                            <input id="customCheck1" type="checkbox" checked class="custom-control-input">
                                        <button type="submit" class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">
                                            {% if item.todo_name %}
                                                Edit Item
                                            {% else %}
                                                Add Item
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

{% block script %}
    <script>
         $('#id_todo_name').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','Task Name')
        $('#id_start_date').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','Start Date')
        $('#id_end_date').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','End Date')
    </script>
{% endblock %}

todoList/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
  <link rel="shortcut icon" href={% static 'images/favicon.ico' %}/>
</head>
<body>
  {% if request.user.is_authenticated %}
  <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
      <div class="d-flex justify-content-between w-100">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/dashboard">Dashboard</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/add-item">Add Item</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/activities">Activity</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/friends-todo">Friends Todo</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/explore">Explore</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/followers">Followers</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/friends">Friends</a>
          </li>
          <li class="nav-item active"><span class="pr-3"></span></li>
          <li class="nav-item active">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
        </ul>
        <h4 class="text-white mb-0 mt-1">{{request.user.first_name}} {{request.user.last_name}}</h3>
      </div>
    </div>
  </nav>
  {% endif %}

  {% block content %}
  {% endblock %}
  
  <script src={% static "js/jquery.min.js" %}></script>
  <script src={% static "js/popper.min.js" %}></script>
  <script src={% static "js/bootstrap.min.js" %}></script>
  {% block script %}
  {% endblock %}
</body>
</html>

todoList/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <h2>Already Login <a href="/dashboard">Go to Dashobard</a></h2>
    {% else %}
        <h1>login</h1>
        <form action="." method="post">
            {{form.as_p}}
            {% csrf_token %}
            <!-- {% for user in users %}
            {{user.email}}
            {{user.first_name}}
            {{user.last_name}}<br />
            {% endfor %} -->
            <button type="submit">Submit</button>
            <br/>
                <b>OR</b>
            <br />
            <a href="/register">Register</a>
        </form>
    {% endif %}
</body>
</html>

todoList/templates/todo-screens/activities.html
{% extends 'base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="container">
        <div class="pt-3">
            <h2>Activites</h2>
            <ul class="list-group">
                {% for activity in activities reversed %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <span>
                            <span><b>{{activity.action_name}}</b> <span style="font-size:14px;color:gray;margin-left:20px;">{{activity.created}}</span></span><br />
                            <p>{{activity.action_detail}}</p>
                        </span>
                        <div class="btn-group">
                            <a href="/remove-activity/{{activity.id}}" class="btn btn-danger">Delete</a>
                        </div>
                    </li>
                {% endfor %}
                
                {% if  activities|length == 0 %}
                    <h2 class="text-center">No activity Found</h2>
                {% endif %}
                    
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

todoList/templates/todo-screens/dashboard.html
{% extends 'base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="container">
        <div class="pt-3">
            <h2>Dashboard</h2>
            <ul class="list-group">
                {% for todo in todo_list reversed %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <span><b>{{forloop.counter}}.</b> {{todo.todo_name}}</span>
                        <div class="btn-group">
                            <a href="/edit-item/{{todo.id}}" class="btn btn-primary">Edit</a>
                            <a href="/remove-item/{{todo.id}}" class="btn btn-danger">Delete</a>
                        </div>
                    </li>
                {% endfor %}
                
                {% if  todo_list|length == 0 %}
                    <h2 class="text-center">No Data Found</h2>
                {% endif %}
                    
            </ul>
        </div>
    </div>
    {% else %}
        <h2>User Not login <a href="/">Login</a></h2>
        <br />
        <b>OR</b>
        <br />
        <a href="register/">Register</a>
    {% endif %}
{% endblock %}

todoList/templates/todo-screens/explore.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="container">
        <div class="pt-3">
            <h2>Activites</h2>
            <ul class="list-group flex-row">
                {% for user in users reversed %}
                    <li style="flex:0 0 30%;margin-right:15px;margin-bottom:15px;" class="list-group-item d-flex align-items-center border-0 p-0">
                        <input class="userId" type="hidden" value="{{user.id}}">
                        <div class="card">
                            <img class="card-img-top" src="{% static 'images/img_avatar1.png' %}" alt="Card image" style="width:100%">
                            <div class="card-body">
                                <h4 class="card-title">{{user.first_name}} {{user.last_name}} 
                                    {% if user.is_superuser == 1 %}
                                        <span style="font-weight: bold;color: grey;font-size: 14px;margin-top: 5px;vertical-align: top;display: inline-block;">(Admin)</span>
                                    {% endif %}
                                </h4>
                              <a class="follow" href="javascript:void(0)" class="btn btn-primary stretched-link">Follow</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                
                {% if  users|length == 0 %}
                    <h2 class="text-center">No Users Found</h2>
                {% endif %}
                    
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block script %}
  <script>
        $('.follow').on('click', function() {
            let userData = $(this).parents('li').children('.userId').val();
            console.log(userData)
            $.ajax({
                type:'GET',
                url:'/follow/',
                dataType : "json",
                contentType: "application/json; charset=utf-8",
                data:{'selected_user_id':userData},
                success: function(response) {
                    console.log(response)
                }
            })
        })
  </script>
{% endblock %}

todoList/templates/todo-screens/followers.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="container">
        <div class="pt-3">
            <h2>Follower</h2>
            <ul class="list-group flex-row">
                {% for follower in followers reversed %}
                    <li id="user{{follower.user.id}}" style="flex:0 0 23%;margin-right:15px;margin-bottom:15px;" class="list-group-item d-flex align-items-center border-0 p-0">
                        <input class="userId" type="hidden" value="{{follower.user.id}}">
                        <div class="card" style="min-height: 359px;">
                            <img class="card-img-top" src="{% static 'images/img_avatar1.png' %}" alt="Card image" style="width:100%">
                            <div class="card-body">
                                <h4 class="card-title" style="white-space: nowrap;width: calc(100% - 58px);overflow: hidden;text-overflow: ellipsis;display: inline-block;font-size: 22px;">{{follower.user.first_name}} {{follower.user.last_name}}</h4>
                                {% if follower.user.is_superuser == 1 %}
                                    <span style="font-weight: bold;color: grey;font-size: 14px;margin-top:2px;vertical-align: top;display: inline-block;">(Admin)</span>
                                {% endif %}
                                {% load checkAlreadyFollow %}
                                {% if request|checkAlreadyFollow:follower.user.id == 0 %}
                                    <a class="follow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Follow</a>
                                {% else %}
                                    <a class="unfollow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Unfollow</a>
                                {% endif %}

                            </div>
                        </div>
                    </li>
                {% endfor %}
                
                {% if  followers|length == 0 %}
                    <h2 class="text-center">No followers Found</h2>
                {% endif %}
                    
            </ul>
        </div>
        <hr />
        <hr />
        <div class="pt-3">
            <h2>Following</h2>
            <ul class="list-group flex-row">
                {% for following in followings reversed %}
                    <li id="user{{following.following_user.id}}" style="flex:0 0 23%;margin-right:15px;margin-bottom:15px;" class="list-group-item d-flex align-items-center border-0 p-0">
                        <input class="userId" type="hidden" value="{{following.following_user.id}}">
                        <div class="card" style="min-height: 359px;">
                            <img class="card-img-top" src="{% static 'images/img_avatar1.png' %}" alt="Card image" style="width:100%">
                            <div class="card-body">
                                <h4 class="card-title" style="white-space: nowrap;width: calc(100% - 58px);overflow: hidden;text-overflow: ellipsis;display: inline-block;font-size: 22px;">{{following.following_user.first_name}} {{following.following_user.last_name}}</h4>
                                {% if following.following_user.is_superuser == 1 %}
                                    <span style="font-weight: bold;color: grey;font-size: 14px;margin-top:2px;vertical-align: top;display: inline-block;">(Admin)</span>
                                {% endif %}
                                {% load checkAlreadyFollow %}
                                {% if request|checkAlreadyFollow:following.following_user.id == 0 %}
                                    <a class="follow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Follow</a>
                                {% else %}
                                    <a class="unfollow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Unfollow</a>
                                {% endif %}

                            </div>
                        </div>
                    </li>
                {% endfor %}
                
                {% if followings|length == 0 %}
                    <h2 class="text-center">No Followings Found</h2>
                {% endif %}
                    
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block script %}
  <script>
    // follow user
    $(document).on('click', '.follow' , function() {
        thisScope = $(this);
        let userData = $(this).parents('li').children('.userId').val();
        $.ajax({
            type:'GET',
            url:'/follow/',
            dataType : "json",
            contentType: "application/json; charset=utf-8",
            data:{'selected_user_id':userData},
            success: function(response) {
                if(response.code == 200){
                    window.location.reload();
                    thisScope.removeClass('follow').addClass('unfollow').text('Unfollow');
                }
            }
        })
    });

    // unfollow user
    $(document).on('click', '.unfollow', function() {
        thisScope = $(this);
        let userData = $(this).parents('li').children('.userId').val();
        $.ajax({
            type:'GET',
            url:'/unfollow/',
            dataType : "json",
            contentType: "application/json; charset=utf-8",
            data:{'selected_user_id':userData},
            success: function(response) {
                if(response.code == 200){
                    window.location.reload();
                    thisScope.removeClass('unfollow').addClass('follow').text('Follow');
                }
            }
        })
    })
  </script>
{% endblock %}

todoList/templates/todo-screens/friends.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <div class="container">
        <div class="pt-3">
            <h2>Friends</h2>
            <ul class="list-group flex-row">
                {% for friend in friends reversed %}
                    <li id="user{{friend.following_user.id}}" style="flex:0 0 23%;margin-right:15px;margin-bottom:15px;" class="list-group-item d-flex align-items-center border-0 p-0">
                        <input class="userId" type="hidden" value="{{friend.following_user.id}}">
                        <div class="card" style="min-height: 359px;">
                            <img class="card-img-top" src="{% static 'images/img_avatar1.png' %}" alt="Card image" style="width:100%">
                            <div class="card-body">
                                <h4 class="card-title" style="white-space: nowrap;width: calc(100% - 58px);overflow: hidden;text-overflow: ellipsis;display: inline-block;font-size: 22px;">{{friend.following_user.first_name}} {{friend.following_user.last_name}}</h4>
                                {% if friend.following_user.is_superuser == 1 %}
                                    <span style="font-weight: bold;color: grey;font-size: 14px;margin-top:2px;vertical-align: top;display: inline-block;">(Admin)</span>
                                {% endif %}
                                {% load checkAlreadyFollow %}
                                {% if request|checkAlreadyFollow:friend.following_user.id == 0 %}
                                    <a class="follow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Friend/Follow</a>
                                {% else %}
                                    <a class="unfollow" style="display:block;" href="javascript:void(0)" class="btn btn-primary stretched-link">Unfriend/Unfollow</a>
                                {% endif %}

                            </div>
                        </div>
                    </li>
                {% endfor %}
                
                {% if  friends|length == 0 %}
                    <h2 class="text-center">No Friend Found</h2>
                {% endif %}
                    
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block script %}
  <script>
    // follow user
    $(document).on('click', '.follow' , function() {
        thisScope = $(this);
        let userData = $(this).parents('li').children('.userId').val();
        $.ajax({
            type:'GET',
            url:'/follow/',
            dataType : "json",
            contentType: "application/json; charset=utf-8",
            data:{'selected_user_id':userData},
            success: function(response) {
                if(response.code == 200){
                    thisScope.removeClass('follow').addClass('unfollow').text('Unfriend/Unfollow');
                }
            }
        })
    });

    // unfollow user
    $(document).on('click', '.unfollow', function() {
        thisScope = $(this);
        let userData = $(this).parents('li').children('.userId').val();
        $.ajax({
            type:'GET',
            url:'/unfollow/',
            dataType : "json",
            contentType: "application/json; charset=utf-8",
            data:{'selected_user_id':userData},
            success: function(response) {
                if(response.code == 200){
                    thisScope.removeClass('unfollow').addClass('follow').text('Friend/Follow');
                }
            }
        })
    })
  </script>
{% endblock %}

todoList/templates/todo-screens/todo-form.html
{% extends 'base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block content %}

        <div class="container-fluid">
                
            <div class="row no-gutter">
                <div class="col-md-12 bg-light">
                    <div class="login d-flex align-items-center py-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-10 col-xl-7 mx-auto">
                                    <h3 class="display-4">Add Item</h3>
                                    <form action="." method="post">
                                        {% csrf_token %}
                                        <div class="form-group mb-3">
                                            {{ form.todo_name }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.start_date }}
                                        </div>
                                        <div class="form-group mb-3">
                                            {{ form.end_date }}
                                        </div>
                                        <div class="custom-control custom-checkbox mb-3 pl-0">
                                            <input id="customCheck1" type="checkbox" checked class="custom-control-input">
                                        <button type="submit" class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">
                                            {% if item.todo_name %}
                                                Edit Item
                                            {% else %}
                                                Add Item
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

{% block script %}
    <script>
         $('#id_todo_name').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','Task Name')
        $('#id_start_date').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','Start Date')
        $('#id_end_date').addClass('form-control rounded-pill border-0 shadow-sm px-4').attr('placeholder','End Date')
    </script>
{% endblock %}